import { InstitutionCategory, DonationType } from "./types";

export interface InstitutionSeed {
  name: string;
  category: InstitutionCategory;
  description: string;
  address: string;
  city: string;
  lat: number;
  lng: number;
  phone: string | null;
  email: string | null;
  website: string | null;
  working_hours: string | null;
  drop_off_hours: string | null;
  accepts_donations: DonationType[];
  capacity: string | null;
  served_population: string;
  is_location_hidden: boolean;
  approximate_area: string | null;
  nearest_zet_stop: string | null;
  zet_lines: string | null;
}

export const INSTITUTIONS: InstitutionSeed[] = [
  // HOMELESS SHELTERS & OVERNIGHT STAYS
  {
    name: "Prihvatilište za beskućnike Crvenog križa",
    category: "homeless_shelter",
    description:
      "Prihvatilište pruža usluge privremenog smještaja beskućnicima s područja Grada Zagreba. Osigurava 24-satni smještaj, tri obroka dnevno, održavanje osobne higijene, medicinsku pomoć, psihosocijalnu podršku i pomoć pri resocijalizaciji. Zahtjev za smještaj podnosi se u HCZSR.",
    address: "Domovinska ulica 10, Velika Kosnica",
    city: "Zagreb",
    lat: 45.7195,
    lng: 16.002,
    phone: "01 62 32 283",
    email: "prihvatiliste@ckzg.hr",
    website: "https://ckzg.hr/prihvatiliste-za-beskucnike/",
    working_hours: "Non-stop (24/7)",
    drop_off_hours: "Svaki dan 9:00-17:00",
    accepts_donations: ["clothes", "food", "hygiene", "blankets_bedding", "medical_supplies", "money"],
    capacity: "94 kreveta",
    served_population: "Beskućnici — odrasle osobe",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Terminal Velika Kosnica",
    zet_lines: "Bus 268",
  },
  {
    name: "Prihvatilište Caritasa Zagrebačke nadbiskupije",
    category: "homeless_shelter",
    description:
      "Beskućnicima se nudi 24-satni smještaj s tri obroka, pomoć u odjeći i obući, higijenske potrepštine, posredovanje pri ishodovanju dokumenata, pomoć pri ostvarivanju prava, karijerno savjetovanje, besplatna pravna pomoć, psihološka i psihijatrijska pomoć.",
    address: "Dugoselska 71, Sesvetski Kraljevec",
    city: "Zagreb",
    lat: 45.8273,
    lng: 16.1185,
    phone: "01 4678 656",
    email: "kuca.beskucnici@czn.hr",
    website: "https://czn.hr",
    working_hours: "Non-stop (24/7)",
    drop_off_hours: "Pon-Pet 8:00-16:00",
    accepts_donations: ["clothes", "food", "hygiene", "blankets_bedding", "furniture", "money", "time"],
    capacity: "21 korisnik",
    served_population: "Beskućnici — cijela Hrvatska",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Sesvetski Kraljevec",
    zet_lines: "Bus 281",
  },
  {
    name: "Prenoćište Dobri dom — Ilica",
    category: "homeless_shelter",
    description:
      "Prenoćište u centru grada nudi noćenje od 19:00 do 9:00 s toplim obrokom i napitkom. Korisnicima su osigurani kuponi za korištenje Javnog kupališta Diana. Dostupno savjetovanje sa socijalnim radnicima.",
    address: "Ilica 29, Zagreb",
    city: "Zagreb",
    lat: 45.8128,
    lng: 15.9687,
    phone: null,
    email: null,
    website: "https://www.dobri-dom.hr",
    working_hours: "19:00-09:00 (noćenje)",
    drop_off_hours: "Kontaktirajte unaprijed",
    accepts_donations: ["clothes", "hygiene", "blankets_bedding", "food"],
    capacity: "20 kreveta",
    served_population: "Beskućnici — noćni smještaj",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Frankopanska",
    zet_lines: "Tram 6, 11, 12, 13, 14",
  },
  // DAY CENTERS FOR HOMELESS
  {
    name: "Udruga Pet Plus — dnevni boravak",
    category: "homeless_shelter",
    description:
      "Dnevni boravak za beskućnike pri Hrvatskoj mreži za beskućnike. Pruža dnevni prostor, topli obrok, savjetovanje i psihosocijalnu podršku za osobe bez doma.",
    address: "Ščitarjevska 11, Zagreb",
    city: "Zagreb",
    lat: 45.7815,
    lng: 15.988,
    phone: "01 4828 401",
    email: null,
    website: null,
    working_hours: "Pon-Pet 8:00-16:00",
    drop_off_hours: "Pon-Pet 8:00-15:00",
    accepts_donations: ["food", "clothes", "hygiene", "money"],
    capacity: null,
    served_population: "Beskućnici — dnevni boravak",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Savišće",
    zet_lines: "Bus 220",
  },
  {
    name: "Udruga Dom nade — poludnevni boravak",
    category: "homeless_shelter",
    description:
      "Poludnevni boravak za beskućnike s programima resocijalizacije, savjetovanjem i materijalnom pomoći.",
    address: "Harambašićeva 20, Zagreb",
    city: "Zagreb",
    lat: 45.8095,
    lng: 15.991,
    phone: "095 378 5403",
    email: null,
    website: null,
    working_hours: "Pon-Pet 8:00-14:00",
    drop_off_hours: "Pon-Pet 8:00-14:00",
    accepts_donations: ["food", "clothes", "hygiene"],
    capacity: null,
    served_population: "Beskućnici — poludnevni boravak",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Harambašićeva",
    zet_lines: "Tram 7, 4",
  },
  // SOUP KITCHENS
  {
    name: "Pučka kuhinja Dobri dom — Branimirova",
    category: "soup_kitchen",
    description:
      "Najveća zagrebačka pučka kuhinja. Dnevno se priprema i servira preko 200 toplih obroka za beskućnike i socijalno ugrožene građane. Obroci su besplatni.",
    address: "Branimirova 35, Zagreb",
    city: "Zagreb",
    lat: 45.8053,
    lng: 15.983,
    phone: null,
    email: null,
    website: "https://www.dobri-dom.hr",
    working_hours: "Pon-Ned 11:00-14:00",
    drop_off_hours: "Pon-Pet 8:00-10:00 (donacije hrane)",
    accepts_donations: ["food", "money", "time"],
    capacity: "200+ obroka dnevno",
    served_population: "Beskućnici i socijalno ugroženi",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Glavni kolodvor",
    zet_lines: "Tram 2, 4, 6, 9, 13",
  },
  {
    name: "Pučka kuhinja Dobri dom — Cerska",
    category: "soup_kitchen",
    description:
      "Podružnica pučke kuhinje za pripremu i podjelu besplatnih toplih obroka socijalno ugroženim građanima.",
    address: "Cerska 3, Zagreb",
    city: "Zagreb",
    lat: 45.8028,
    lng: 15.9622,
    phone: null,
    email: null,
    website: "https://www.dobri-dom.hr",
    working_hours: "Pon-Ned 11:00-14:00",
    drop_off_hours: "Pon-Pet 8:00-10:00",
    accepts_donations: ["food", "money", "time"],
    capacity: null,
    served_population: "Beskućnici i socijalno ugroženi",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Savska cesta",
    zet_lines: "Tram 4, 9, 14",
  },
  {
    name: "Pučka kuhinja Dobri dom — Alfirevićeva",
    category: "soup_kitchen",
    description:
      "Podružnica pučke kuhinje za pripremu i podjelu besplatnih toplih obroka socijalno ugroženim građanima.",
    address: "Alfirevićeva 6, Zagreb",
    city: "Zagreb",
    lat: 45.8152,
    lng: 15.9933,
    phone: null,
    email: null,
    website: "https://www.dobri-dom.hr",
    working_hours: "Pon-Ned 11:00-14:00",
    drop_off_hours: "Pon-Pet 8:00-10:00",
    accepts_donations: ["food", "money", "time"],
    capacity: null,
    served_population: "Beskućnici i socijalno ugroženi",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Kvaternikov trg",
    zet_lines: "Tram 4, 7, 11, 12",
  },
  {
    name: "Pučka kuhinja župe Sv. Antuna Padovanskog",
    category: "soup_kitchen",
    description:
      "Župna pučka kuhinja na Svetom Duhu koja osigurava tople obroke za beskućnike i socijalno ugrožene. Vodi se kao pastoralna inicijativa.",
    address: "Sveti Duh 31, Zagreb",
    city: "Zagreb",
    lat: 45.8198,
    lng: 15.9438,
    phone: null,
    email: null,
    website: null,
    working_hours: "Raspitajte se u župi",
    drop_off_hours: "Raspitajte se u župi",
    accepts_donations: ["food", "money"],
    capacity: null,
    served_population: "Beskućnici i socijalno ugroženi",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Sveti Duh",
    zet_lines: "Tram 2, 6; Bus 102",
  },
  {
    name: "Socijalna samoposluga Caritasa",
    category: "soup_kitchen",
    description:
      "Prva socijalna samoposluga u Hrvatskoj, otvorena 2009. Socijalno ugroženi pojedinci besplatno preuzimaju prehrambene proizvode i potrepštine.",
    address: "Crnojezerska 20, Zagreb",
    city: "Zagreb",
    lat: 45.7975,
    lng: 15.951,
    phone: "01 3457 175",
    email: "soc.samoposluga@czn.hr",
    website: "https://czn.hr",
    working_hours: "Pon-Pet 8:00-15:00",
    drop_off_hours: "Pon-Pet 8:00-14:00",
    accepts_donations: ["food", "hygiene", "baby_items", "money"],
    capacity: null,
    served_population: "Socijalno ugroženi pojedinci i obitelji",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Knežija",
    zet_lines: "Tram 5, 17; Bus 109",
  },
  // CHILDREN'S HOMES — ZAGREB
  {
    name: "Dom za djecu Zagreb — Nazorova",
    category: "children_home",
    description:
      "Najveći dom za djecu bez odgovarajuće roditeljske skrbi u Zagrebu. Pruža smještaj, odgoj, obrazovanje i stručnu podršku djeci od predškolske dobi do završetka školovanja. Djeca su uključena u redoviti obrazovni sustav.",
    address: "Nazorova 49, Zagreb",
    city: "Zagreb",
    lat: 45.814,
    lng: 15.9643,
    phone: "01/4821-702",
    email: null,
    website: null,
    working_hours: "Non-stop (24/7 — djeca žive ovdje)",
    drop_off_hours: "Pon-Pet 9:00-16:00",
    accepts_donations: ["clothes", "toys_books", "school_supplies", "food", "money", "time"],
    capacity: "Više podružnica u Zagrebu",
    served_population: "Djeca bez roditeljske skrbi (3-18 godina)",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Nazorova",
    zet_lines: "Tram 8, 14; Bus 102",
  },
  {
    name: "Dom za djecu Zagreb — podružnica I.G. Kovačić",
    category: "children_home",
    description:
      "Podružnica Doma za djecu Zagreb u središtu grada. Pruža obiteljsko okruženje za djecu bez odgovarajuće roditeljske skrbi.",
    address: "I.G. Kovačića 23, Zagreb",
    city: "Zagreb",
    lat: 45.8112,
    lng: 15.9665,
    phone: "01/4834-536",
    email: null,
    website: null,
    working_hours: "Non-stop",
    drop_off_hours: "Pon-Pet 9:00-16:00",
    accepts_donations: ["clothes", "toys_books", "school_supplies", "food", "money", "time"],
    capacity: null,
    served_population: "Djeca bez roditeljske skrbi",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Frankopanska",
    zet_lines: "Tram 6, 11, 12",
  },
  {
    name: "Dom za djecu Zagreb — podružnica A.G. Matoš",
    category: "children_home",
    description: "Podružnica Doma za djecu Zagreb na Selskoj cesti.",
    address: "Selska cesta 132, Zagreb",
    city: "Zagreb",
    lat: 45.8025,
    lng: 15.94,
    phone: "01/3695-482",
    email: null,
    website: null,
    working_hours: "Non-stop",
    drop_off_hours: "Pon-Pet 9:00-16:00",
    accepts_donations: ["clothes", "toys_books", "school_supplies", "food", "money", "time"],
    capacity: null,
    served_population: "Djeca bez roditeljske skrbi",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Selska",
    zet_lines: "Tram 5, 17",
  },
  {
    name: "Dom za djecu Zagreb — podružnica Laduč",
    category: "children_home",
    description: "Podružnica Doma za djecu Zagreb u Laduču, zapadno od grada.",
    address: "Zagrebačka 106, Laduč",
    city: "Zagreb",
    lat: 45.809,
    lng: 15.834,
    phone: "01/3395-765",
    email: null,
    website: null,
    working_hours: "Non-stop",
    drop_off_hours: "Pon-Pet 9:00-15:00",
    accepts_donations: ["clothes", "toys_books", "school_supplies", "food", "money", "time"],
    capacity: null,
    served_population: "Djeca bez roditeljske skrbi",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: null,
    zet_lines: null,
  },
  {
    name: "Kuća sv. Franje — Caritas (djeca)",
    category: "children_home",
    description:
      "Kuća pruža uslugu skrbi o djeci bez odgovarajuće roditeljske skrbi, primarno starije predškolske i osnovnoškolske dobi, kao i srednjoškolskog uzrasta do punoljetnosti. Kapacitet 34 korisnika. Djeci se osigurava sigurno okruženje, prehrana, zdravstvena skrb, stručna podrška i uključenost u redoviti obrazovni sustav. Od 1972. godine.",
    address: "Vugrovec Augusta Šenoe 52, Sesvete",
    city: "Zagreb",
    lat: 45.8538,
    lng: 16.0682,
    phone: "01/2044-010",
    email: "kuca.vugrovec@czn.hr",
    website: "https://czn.hr",
    working_hours: "Non-stop",
    drop_off_hours: "Pon-Pet 8:00-16:00",
    accepts_donations: ["clothes", "toys_books", "school_supplies", "food", "hygiene", "money", "time"],
    capacity: "34 djece",
    served_population: "Djeca bez roditeljske skrbi (predškolska do 18 god.)",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Vugrovec",
    zet_lines: "Bus 225",
  },
  {
    name: "Kuća ljubavi — Caritas (trudnice i bebe)",
    category: "children_home",
    description:
      "Smještaj za maloljetne i punoljetne trudnice i majke s djecom od rođenja do godine dana kojima je izostala podrška obitelji. Također pruža smještaj djeci bez roditeljske skrbi do treće godine. Radionice brige o djeci, kuhanja, ostvarivanja prava. Prijem putem HCZSR.",
    address: "Budaševska 20, Zagreb",
    city: "Zagreb",
    lat: 45.791,
    lng: 15.985,
    phone: "01/2408-833",
    email: "kuca.ljubavi@czn.hr",
    website: "https://czn.hr",
    working_hours: "Non-stop",
    drop_off_hours: "Pon-Pet 9:00-15:00",
    accepts_donations: ["baby_items", "clothes", "food", "hygiene", "toys_books", "money", "time"],
    capacity: null,
    served_population: "Trudnice, majke s bebama, djeca do 3 godine",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Savica Šanci",
    zet_lines: "Bus 221, 226",
  },
  // CARITAS FACILITIES
  {
    name: "Caritas Zagrebačke nadbiskupije — Socijalna služba",
    category: "caritas",
    description:
      "Pruža stručnu i savjetodavnu pomoć, posreduje u ostvarivanju socijalnih prava, dijeli materijalnu pomoć (hrana, odjeća, obuća, drva za ogrjev, namještaj), financijsku pomoć, te posuđuje bolesnička pomagala. Rad sa strankama: pon i sri 9-12; čet 14-17.",
    address: "Babonićeva 121, Zagreb",
    city: "Zagreb",
    lat: 45.809,
    lng: 15.9372,
    phone: "098/408 536",
    email: "socijalna.sluzba1@czn.hr",
    website: "https://czn.hr",
    working_hours: "Pon, Sri 9:00-12:00; Čet 14:00-17:00",
    drop_off_hours: "Pon-Pet 8:00-15:00",
    accepts_donations: [
      "clothes",
      "food",
      "furniture",
      "hygiene",
      "medical_supplies",
      "blankets_bedding",
      "money",
    ],
    capacity: null,
    served_population: "Svi socijalno ugroženi građani",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Črnomerec",
    zet_lines: "Tram 2, 6; Bus 102, 110",
  },
  {
    name: "Caritas — Obiteljsko savjetovalište",
    category: "caritas",
    description:
      "Savjetovalište za osobe s osobnim, bračnim ili obiteljskim poteškoćama, problemima u odnosima s drugima ili razvojnim teškoćama. Uključuje rad s djecom. Stručna pomoć psihologa i savjetnika.",
    address: "Babonićeva 121, Zagreb",
    city: "Zagreb",
    lat: 45.809,
    lng: 15.9372,
    phone: "098/408 535",
    email: "savjetovaliste.psiholog@czn.hr",
    website: "https://czn.hr",
    working_hours: "Pon, Uto, Sri, Pet 8-16; Čet 10-18",
    drop_off_hours: null,
    accepts_donations: ["money", "time"],
    capacity: null,
    served_population: "Obitelji i pojedinci s poteškoćama",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Črnomerec",
    zet_lines: "Tram 2, 6; Bus 102, 110",
  },
  {
    name: "Caritas — Pomoć u kući starijima",
    category: "elderly_care",
    description:
      "Usluge čišćenja, pranja rublja, pomoć oko osobne higijene, kupovine, pratnja do liječnika, mjerenje tlaka i šećera, pomoć kod kućanskih popravaka. Također pruža pomoć u hrani, odjeći, pokrivačima, higijenskim potrepštinama i lijekovima.",
    address: "Babonićeva 121, Zagreb",
    city: "Zagreb",
    lat: 45.809,
    lng: 15.9372,
    phone: "099/408 536",
    email: "pomocukuci@czn.hr",
    website: "https://czn.hr",
    working_hours: "Pon-Pet 8:00-16:00",
    drop_off_hours: "Pon-Pet 8:00-15:00",
    accepts_donations: ["food", "hygiene", "medical_supplies", "blankets_bedding", "money", "time"],
    capacity: null,
    served_population: "Starije, bolesne i nemoćne osobe",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Črnomerec",
    zet_lines: "Tram 2, 6; Bus 102, 110",
  },
  {
    name: "Misionarke ljubavi — sestre Majke Terezije",
    category: "caritas",
    description:
      "Humanitarna pomoć u hrani, dječjoj hrani, odjeći, obući, higijenskim potrepštinama i pelenama. Psihosocijalna podrška. Samostan sestara Majke Terezije.",
    address: "Jukićeva 24, Zagreb",
    city: "Zagreb",
    lat: 45.8082,
    lng: 15.9668,
    phone: "01/4812 452",
    email: null,
    website: null,
    working_hours: "Raspitajte se na broj telefona",
    drop_off_hours: "Raspitajte se na broj telefona",
    accepts_donations: ["food", "clothes", "hygiene", "baby_items", "blankets_bedding"],
    capacity: null,
    served_population: "Socijalno ugroženi građani",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Vodnikova",
    zet_lines: "Tram 4, 9, 14",
  },
  // DISABILITY SUPPORT
  {
    name: "Kuća Bl. Alojzije Stepinac — Brezovica (djeca s teškoćama)",
    category: "disability_support",
    description:
      "Skrb o djeci s teškoćama u razvoju od 3 do 21 godine (dugotrajni smještaj) i poludnevni boravak za odrasle osobe s invaliditetom. Rehabilitacija, fizioterapija, senzorička integracija, snoezelen room, školske aktivnosti. Kapacitet: 75 na smještaju + 25 na boravku. Od 1994.",
    address: "Brezovička cesta 98, Brezovica",
    city: "Zagreb",
    lat: 45.758,
    lng: 15.919,
    phone: "01/6537 806",
    email: "kuca.brezovica@czn.hr",
    website: "https://czn.hr",
    working_hours: "Non-stop (smještaj); boravak Pon-Pet 8-15",
    drop_off_hours: "Pon-Pet 8:00-15:00",
    accepts_donations: ["clothes", "toys_books", "school_supplies", "hygiene", "furniture", "money", "time"],
    capacity: "75 smještaj + 25 boravak",
    served_population: "Djeca s teškoćama u razvoju (3-21) i odrasli s invaliditetom",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Brezovica",
    zet_lines: "Bus 161",
  },
  {
    name: "Stambena zajednica za osobe s invaliditetom — Trešnjevka",
    category: "disability_support",
    description:
      "Izvaninstitucionalna usluga organiziranog stanovanja za 8 osoba s invaliditetom uz stalnu stručnu pomoć. Cilj: poboljšanje kvalitete života, socijalno uključivanje i izjednačavanje mogućnosti.",
    address: "Nijemčanska 14, Zagreb",
    city: "Zagreb",
    lat: 45.802,
    lng: 15.952,
    phone: "01/2921 110",
    email: "stambena.zajednica@czn.hr",
    website: "https://czn.hr",
    working_hours: "Non-stop",
    drop_off_hours: "Kontaktirajte unaprijed",
    accepts_donations: ["food", "hygiene", "furniture", "money", "time"],
    capacity: "8 korisnika",
    served_population: "Odrasle osobe s invaliditetom",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Knežija",
    zet_lines: "Tram 5, 17",
  },
  // DOMESTIC VIOLENCE SHELTER
  {
    name: "Sigurna kuća — Caritas ZgNd",
    category: "domestic_violence",
    description:
      "Smještaj za žene i djecu — žrtve obiteljskog nasilja. Osigurava sigurno zbrinjavanje, prehranu, zdravstvenu skrb, psihosocijalnu pomoć, savjetovanje, individualni i grupni rad, pomoć pri odgoju djece. Prijem isključivo putem HCZSR. Lokacija je tajna radi sigurnosti korisnica.",
    address: "Tajna lokacija",
    city: "Zagreb",
    lat: 45.8,
    lng: 15.94,
    phone: "01/366 8824",
    email: "sigurna.kuca@czn.hr",
    website: null,
    working_hours: "Non-stop (24/7)",
    drop_off_hours: "Kontaktirajte telefonom",
    accepts_donations: ["clothes", "baby_items", "hygiene", "toys_books", "food", "money"],
    capacity: "19 korisnica",
    served_population: "Žene i djeca — žrtve obiteljskog nasilja",
    is_location_hidden: true,
    approximate_area: "Zagreb — zapad",
    nearest_zet_stop: null,
    zet_lines: null,
  },
  // STUDENT HOUSING SUPPORT
  {
    name: 'Kuća za mlade "Da život imaju!"',
    category: "student_housing",
    description:
      "Smještaj za studente iz obitelji slabijeg imovinskog stanja koji nisu ostvarili pravo na studentski dom. Pruža smještaj, podršku, savjetovanje, stipendije i materijalnu pomoć. Kapacitet: 14 osoba.",
    address: "Selska cesta 165, Zagreb",
    city: "Zagreb",
    lat: 45.8,
    lng: 15.935,
    phone: "01/3758 204",
    email: "kuca.dazivotimaju@czn.hr",
    website: "https://czn.hr",
    working_hours: "Non-stop",
    drop_off_hours: "Pon-Pet 9:00-16:00",
    accepts_donations: ["school_supplies", "food", "money"],
    capacity: "14 studenata",
    served_population: "Studenti iz socijalno ugroženih obitelji",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Selska",
    zet_lines: "Tram 5, 17",
  },
  {
    name: "Organizirano stanovanje za mlade iz alternativne skrbi",
    category: "student_housing",
    description:
      "Stanovanje uz sveobuhvatnu podršku za djecu bez roditeljske skrbi (srednjoškolci do punoljetnosti) i stanovanje uz povremenu podršku za punoljetne osobe koje su odrasle u alternativnoj skrbi. Odgoj temeljen na doživljajnoj pedagogiji. Od 2023.",
    address: "Selska cesta 165, Zagreb",
    city: "Zagreb",
    lat: 45.8,
    lng: 15.935,
    phone: "099/5246-948",
    email: "osmladi@czn.hr",
    website: "https://czn.hr",
    working_hours: "Non-stop",
    drop_off_hours: "Kontaktirajte unaprijed",
    accepts_donations: ["school_supplies", "clothes", "food", "furniture", "money", "time"],
    capacity: "8 + 8 korisnika",
    served_population: "Mladi koji izlaze iz sustava alternativne skrbi",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: "Selska",
    zet_lines: "Tram 5, 17",
  },
  // CHILDREN'S HOMES — REST OF CROATIA
  {
    name: 'Dom za djecu "Sveta Ana" — Vinkovci',
    category: "children_home",
    description: "Dom za djecu bez odgovarajuće roditeljske skrbi u Vinkovcima.",
    address: "Anina 2d, Vinkovci",
    city: "Vinkovci",
    lat: 45.2886,
    lng: 18.7952,
    phone: "032/331-057",
    email: null,
    website: null,
    working_hours: "Non-stop",
    drop_off_hours: "Pon-Pet 9:00-15:00",
    accepts_donations: ["clothes", "toys_books", "school_supplies", "food", "money", "time"],
    capacity: null,
    served_population: "Djeca bez roditeljske skrbi",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: null,
    zet_lines: null,
  },
  {
    name: 'Dom za djecu "Braća Mažuranići" — Novi Vinodolski',
    category: "children_home",
    description: "Dom za djecu bez odgovarajuće roditeljske skrbi u Novom Vinodolskom.",
    address: "A. Mažuranića 5, Novi Vinodolski",
    city: "Novi Vinodolski",
    lat: 45.126,
    lng: 14.7894,
    phone: "051/244-423",
    email: null,
    website: null,
    working_hours: "Non-stop",
    drop_off_hours: "Pon-Pet 9:00-15:00",
    accepts_donations: ["clothes", "toys_books", "school_supplies", "food", "money", "time"],
    capacity: null,
    served_population: "Djeca bez roditeljske skrbi",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: null,
    zet_lines: null,
  },
  {
    name: 'Dom za djecu "I. Brlić Mažuranić" — Lovran',
    category: "children_home",
    description: "Dom za djecu bez odgovarajuće roditeljske skrbi u Lovranu.",
    address: "Omladinska 1, Lovran",
    city: "Lovran",
    lat: 45.2917,
    lng: 14.2723,
    phone: "051/291-521",
    email: null,
    website: null,
    working_hours: "Non-stop",
    drop_off_hours: "Pon-Pet 9:00-15:00",
    accepts_donations: ["clothes", "toys_books", "school_supplies", "food", "money", "time"],
    capacity: null,
    served_population: "Djeca bez roditeljske skrbi",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: null,
    zet_lines: null,
  },
  {
    name: 'Dom za djecu "Izvor" — Selce',
    category: "children_home",
    description: "Dom za djecu bez odgovarajuće roditeljske skrbi u Selcu.",
    address: "E. Antića 20, Selce",
    city: "Selce",
    lat: 45.158,
    lng: 14.721,
    phone: "051/765-095",
    email: null,
    website: null,
    working_hours: "Non-stop",
    drop_off_hours: "Pon-Pet 9:00-15:00",
    accepts_donations: ["clothes", "toys_books", "school_supplies", "food", "money", "time"],
    capacity: null,
    served_population: "Djeca bez roditeljske skrbi",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: null,
    zet_lines: null,
  },
  {
    name: 'Dom za djecu "Klasje" — Osijek',
    category: "children_home",
    description: "Dom za djecu bez odgovarajuće roditeljske skrbi u Osijeku.",
    address: "Ružina 32, Osijek",
    city: "Osijek",
    lat: 45.555,
    lng: 18.6835,
    phone: "031/373-688",
    email: null,
    website: null,
    working_hours: "Non-stop",
    drop_off_hours: "Pon-Pet 9:00-15:00",
    accepts_donations: ["clothes", "toys_books", "school_supplies", "food", "money", "time"],
    capacity: null,
    served_population: "Djeca bez roditeljske skrbi",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: null,
    zet_lines: null,
  },
  {
    name: 'Dom za djecu "Lipik"',
    category: "children_home",
    description: "Dom za djecu bez odgovarajuće roditeljske skrbi u Lipiku.",
    address: "Matije Gupca 3, Lipik",
    city: "Lipik",
    lat: 45.4088,
    lng: 17.1505,
    phone: "034/421-115",
    email: null,
    website: null,
    working_hours: "Non-stop",
    drop_off_hours: "Pon-Pet 9:00-15:00",
    accepts_donations: ["clothes", "toys_books", "school_supplies", "food", "money", "time"],
    capacity: null,
    served_population: "Djeca bez roditeljske skrbi",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: null,
    zet_lines: null,
  },
  {
    name: 'Dom za djecu "Maestral" — Split',
    category: "children_home",
    description: "Dom za djecu bez odgovarajuće roditeljske skrbi u Splitu.",
    address: "Jurja Šižgorića 4, Split",
    city: "Split",
    lat: 43.5125,
    lng: 16.4505,
    phone: "021/539-157",
    email: null,
    website: null,
    working_hours: "Non-stop",
    drop_off_hours: "Pon-Pet 9:00-15:00",
    accepts_donations: ["clothes", "toys_books", "school_supplies", "food", "money", "time"],
    capacity: null,
    served_population: "Djeca bez roditeljske skrbi",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: null,
    zet_lines: null,
  },
  {
    name: 'Dom za djecu "Maslina" — Dubrovnik',
    category: "children_home",
    description: "Dom za djecu bez odgovarajuće roditeljske skrbi u Dubrovniku.",
    address: "Vlahe Bukovca 5, Dubrovnik",
    city: "Dubrovnik",
    lat: 42.651,
    lng: 18.087,
    phone: "020/416-704",
    email: null,
    website: null,
    working_hours: "Non-stop",
    drop_off_hours: "Pon-Pet 9:00-15:00",
    accepts_donations: ["clothes", "toys_books", "school_supplies", "food", "money", "time"],
    capacity: null,
    served_population: "Djeca bez roditeljske skrbi",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: null,
    zet_lines: null,
  },
  {
    name: 'Dom za djecu "Pula"',
    category: "children_home",
    description: "Dom za djecu bez odgovarajuće roditeljske skrbi u Puli.",
    address: "Pino Budićin 17, Pula",
    city: "Pula",
    lat: 44.8697,
    lng: 13.841,
    phone: "052/211-192",
    email: null,
    website: null,
    working_hours: "Non-stop",
    drop_off_hours: "Pon-Pet 9:00-15:00",
    accepts_donations: ["clothes", "toys_books", "school_supplies", "food", "money", "time"],
    capacity: null,
    served_population: "Djeca bez roditeljske skrbi",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: null,
    zet_lines: null,
  },
  {
    name: 'Dom za djecu "Svitanje" — Koprivnica',
    category: "children_home",
    description: "Dom za djecu bez odgovarajuće roditeljske skrbi u Koprivnici.",
    address: "Đure Basaričeka 13, Koprivnica",
    city: "Koprivnica",
    lat: 46.1628,
    lng: 16.8311,
    phone: "048/621-034",
    email: null,
    website: null,
    working_hours: "Non-stop",
    drop_off_hours: "Pon-Pet 9:00-15:00",
    accepts_donations: ["clothes", "toys_books", "school_supplies", "food", "money", "time"],
    capacity: null,
    served_population: "Djeca bez roditeljske skrbi",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: null,
    zet_lines: null,
  },
  {
    name: 'Dom za djecu "Vladimir Nazor" — Karlovac',
    category: "children_home",
    description: "Dom za djecu bez odgovarajuće roditeljske skrbi u Karlovcu.",
    address: "Nazorova 10, Karlovac",
    city: "Karlovac",
    lat: 45.4906,
    lng: 15.5494,
    phone: "047/617-031",
    email: null,
    website: null,
    working_hours: "Non-stop",
    drop_off_hours: "Pon-Pet 9:00-15:00",
    accepts_donations: ["clothes", "toys_books", "school_supplies", "food", "money", "time"],
    capacity: null,
    served_population: "Djeca bez roditeljske skrbi",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: null,
    zet_lines: null,
  },
  {
    name: 'Dom za djecu "Vrbina" — Sisak',
    category: "children_home",
    description: "Dom za djecu bez odgovarajuće roditeljske skrbi u Sisku.",
    address: "Tomislavova 16, Sisak",
    city: "Sisak",
    lat: 45.4831,
    lng: 16.3728,
    phone: "044/545-320",
    email: null,
    website: null,
    working_hours: "Non-stop",
    drop_off_hours: "Pon-Pet 9:00-15:00",
    accepts_donations: ["clothes", "toys_books", "school_supplies", "food", "money", "time"],
    capacity: null,
    served_population: "Djeca bez roditeljske skrbi",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: null,
    zet_lines: null,
  },
  {
    name: "Dom za djecu Slavonski Brod",
    category: "children_home",
    description: "Dom za djecu bez odgovarajuće roditeljske skrbi u Slavonskom Brodu.",
    address: "Kumičićeva 37, Slavonski Brod",
    city: "Slavonski Brod",
    lat: 45.158,
    lng: 18.0108,
    phone: "035/448-690",
    email: null,
    website: null,
    working_hours: "Non-stop",
    drop_off_hours: "Pon-Pet 9:00-15:00",
    accepts_donations: ["clothes", "toys_books", "school_supplies", "food", "money", "time"],
    capacity: null,
    served_population: "Djeca bez roditeljske skrbi",
    is_location_hidden: false,
    approximate_area: null,
    nearest_zet_stop: null,
    zet_lines: null,
  },
];
