import type { Framework } from "@/lib/types";
import type { ManifestDatapoint } from "./types";

/** Per-framework datapoint definitions (labels + which calculator to run). */
export const FRAMEWORK_MANIFESTS: Record<Framework, ManifestDatapoint[]> = {
  vsme_basic: [
    {
      id: "VSME-B1-volunteer-hours",
      framework: "vsme_basic",
      label_en: "Total company-attributed volunteer hours (recorded)",
      label_hr: "Ukupno sati volontiranja (evidentirano, tvrtka)",
      unit: "hours",
      compute: "volunteer_hours_sum",
      required: true,
    },
    {
      id: "VSME-B2-acknowledged-giving",
      framework: "vsme_basic",
      label_en: "Acknowledged in-kind / pledged value (EUR, fiscal period)",
      label_hr: "Potvrđene donacije (EUR, razdoblje)",
      unit: "EUR",
      compute: "pledges_acknowledged_eur",
      required: true,
    },
    {
      id: "VSME-B3-volunteer-sessions",
      framework: "vsme_basic",
      label_en: "Volunteer sessions completed (check-out rows)",
      label_hr: "Broj završenih volonterskih sesija",
      unit: "count",
      compute: "volunteer_sessions_count",
      required: false,
    },
  ],
  vsme_comp: [
    {
      id: "VSME-C-volunteer-hours",
      framework: "vsme_comp",
      label_en: "Volunteer hours (company scope)",
      label_hr: "Sati volontiranja (doseg tvrtke)",
      unit: "hours",
      compute: "volunteer_hours_sum",
      required: true,
    },
    {
      id: "VSME-C-ack-eur",
      framework: "vsme_comp",
      label_en: "Acknowledged contributions (EUR)",
      label_hr: "Potvrđeni doprinosi (EUR)",
      unit: "EUR",
      compute: "pledges_acknowledged_eur",
      required: true,
    },
    {
      id: "VSME-C-members",
      framework: "vsme_comp",
      label_en: "Active company roster (members)",
      label_hr: "Broj članova u programu",
      unit: "count",
      compute: "company_member_count",
      required: false,
    },
  ],
  esrs_s1: [
    {
      id: "ESRS-S1-volunteer-hours",
      framework: "esrs_s1",
      label_en: "S1 — Workforce / community: volunteer hours",
      label_hr: "S1 — Volonterski sati",
      unit: "hours",
      compute: "volunteer_hours_sum",
      required: true,
    },
    {
      id: "ESRS-S1-ack-count",
      framework: "esrs_s1",
      label_en: "S1 — Acknowledged pledge events (count)",
      label_hr: "S1 — Broj potvrđenih zavjeta",
      unit: "count",
      compute: "pledges_acknowledged_count",
      required: false,
    },
  ],
  esrs_s3: [
    {
      id: "ESRS-S3-community-investment",
      framework: "esrs_s3",
      label_en: "S3 — Community: acknowledged EUR (proxy)",
      label_hr: "S3 — Zajednica: EUR (proxy)",
      unit: "EUR",
      compute: "pledges_acknowledged_eur",
      required: true,
    },
    {
      id: "ESRS-S3-volunteer-sessions",
      framework: "esrs_s3",
      label_en: "S3 — Volunteer sessions",
      label_hr: "S3 — Volonterske sesije",
      unit: "count",
      compute: "volunteer_sessions_count",
      required: false,
    },
  ],
  gri_413: [
    {
      id: "GRI-413-1-hours",
      framework: "gri_413",
      label_en: "GRI 413-1 — Volunteer hours (company programmes)",
      label_hr: "GRI 413-1 — Sati volontiranja",
      unit: "hours",
      compute: "volunteer_hours_sum",
      required: true,
    },
    {
      id: "GRI-413-1-sessions",
      framework: "gri_413",
      label_en: "GRI 413-1 — Programme sessions (check-outs)",
      label_hr: "GRI 413-1 — Sesije programa",
      unit: "count",
      compute: "volunteer_sessions_count",
      required: false,
    },
  ],
  b4si: [
    {
      id: "B4SI-time-input",
      framework: "b4si",
      label_en: "B4SI / Inputs — Time (volunteer hours)",
      label_hr: "B4SI — Ulaganje vremena (sati)",
      unit: "hours",
      compute: "volunteer_hours_sum",
      required: true,
    },
    {
      id: "B4SI-money-proxy",
      framework: "b4si",
      label_en: "B4SI — Cash / in-kind proxy (ack EUR)",
      label_hr: "B4SI — Novčani proxy (potvrđeni EUR)",
      unit: "EUR",
      compute: "pledges_acknowledged_eur",
      required: true,
    },
    {
      id: "B4SI-active-campaigns",
      framework: "b4si",
      label_en: "B4SI — Active giving campaigns",
      label_hr: "B4SI — Aktivne kampanje",
      unit: "count",
      compute: "campaigns_active_count",
      required: false,
    },
  ],
};
