import type { VolunteerEventCardProps } from "@/components/VolunteerEventCard";

/** Static rows for `/demo/volunteer-showcase` (showcase / pitch). */
export const DEMO_VOLUNTEER_EVENTS: VolunteerEventCardProps["event"][] = [
  {
    id: "demo-event-featured",
    institution_id: "demo-inst-1",
    title: "Community kitchen — lunch service",
    description: "Help serve warm meals and chat with guests.",
    event_date: "2026-05-10",
    start_time: "10:00",
    end_time: "14:00",
    volunteers_needed: 12,
    volunteers_signed_up: 7,
    requirements: "Comfortable standing for a few hours; Croatian or English.",
    contact_person: "Ana Horvat",
    contact_phone: "+385 1 234 5678",
    is_past: false,
    created_at: "2026-04-01T10:00:00.000Z",
    institution: {
      id: "demo-inst-1",
      name: "Zagreb Food Solidarity",
      category: "soup_kitchen",
      address: "Trg bana Jelačića 1",
      city: "Zagreb",
    },
  },
  {
    id: "demo-event-2",
    institution_id: "demo-inst-2",
    title: "Weekend reading club for kids",
    description: "Read stories and help with simple crafts.",
    event_date: "2026-05-17",
    start_time: "09:30",
    end_time: "12:00",
    volunteers_needed: 6,
    volunteers_signed_up: 2,
    requirements: "Background check friendly environment; patience with children.",
    contact_person: "Marko Novak",
    contact_phone: null,
    is_past: false,
    created_at: "2026-04-02T10:00:00.000Z",
    institution: {
      id: "demo-inst-2",
      name: "Sunflower Children's Home",
      category: "children_home",
      address: "Ilica 100",
      city: "Zagreb",
    },
  },
  {
    id: "demo-event-3",
    institution_id: "demo-inst-3",
    title: "Shelter welcome desk & intake",
    description: "Greet arrivals, explain services, light admin.",
    event_date: "2026-05-03",
    start_time: "16:00",
    end_time: "20:00",
    volunteers_needed: 4,
    volunteers_signed_up: 4,
    requirements: "Empathy and discretion required.",
    contact_person: "Ivana Kralj",
    contact_phone: null,
    is_past: false,
    created_at: "2026-04-03T10:00:00.000Z",
    institution: {
      id: "demo-inst-3",
      name: "Night Shelter Zagreb",
      category: "homeless_shelter",
      address: "Savska cesta 50",
      city: "Zagreb",
    },
  },
  {
    id: "demo-event-4",
    institution_id: "demo-inst-4",
    title: "Clothing & hygiene kit packing",
    description: "Sort donations and pack kits for families.",
    event_date: "2026-05-24",
    start_time: "13:00",
    end_time: "17:00",
    volunteers_needed: 15,
    volunteers_signed_up: 5,
    requirements: "Wear comfortable clothes; lifting up to 10 kg.",
    contact_person: "Petra Marić",
    contact_phone: null,
    is_past: false,
    created_at: "2026-04-04T10:00:00.000Z",
    institution: {
      id: "demo-inst-4",
      name: "Caritas Zagreb — Donation centre",
      category: "caritas",
      address: "Kaptol 1",
      city: "Zagreb",
    },
  },
];
